"""add_vehicle_fields_to_user

Revision ID: c896137557d0
Revises: d19f98bcd041
Create Date: 2026-03-08 02:59:51.254731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c896137557d0'
down_revision: Union[str, None] = 'd19f98bcd041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vehicle_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('vehicle_plate', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('vehicle_color', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vehicle_color')
    op.drop_column('users', 'vehicle_plate')
    op.drop_column('users', 'vehicle_type')
    # ### end Alembic commands ###
